namespace: crystian
name: incus
version: 1.1.1
readme: README.md
authors:
- Crystian <Crystian0704>
description: Ansible collection for managing Incus containers and VMs
license:
- MIT
license_file: 'LICENSE'
tags:
  - incus
  - containers
  - virtual-machines
  - virtualization
  - infrastructure
dependencies: {}
repository: https://github.com/Crystian0704/incus-plugin-ansible
documentation: https://github.com/Crystian0704/incus-plugin-ansible/tree/main/docs

homepage: https://github.com/Crystian0704/incus-plugin-ansible

issues: https://github.com/Crystian0704/incus-plugin-ansible/issues

build_ignore:
  - generate_docs.py
  - audit_docs.py
  - tests
  - "*.tar.gz"
  - .gitignore
  - .venv
  - requirements.txt
